@BaseUrl = http://localhost:5134/api

### Get All Books
GET {{BaseUrl}}/books/
Accept: application/json

### Get Book By ID
GET {{BaseUrl}}/books/7
Accept: application/json

### Create Book
POST {{BaseUrl}}/books/
Content-Type: application/json

{
  "title": "A Michael and Me",
  "year": 2025,
  "authorName": "Michael Gathwright"
}


### Update Book
PUT {{BaseUrl}}/books/3
Content-Type: application/json

{
  "id": 3
  "title": "Inception",
  "year": 2014,
  "authorName": "Christopher Nolan"
}

### Delete Book By ID
DELETE {{BaseUrl}}/books/7